all:
	g++ -static -fno-optimize-sibling-calls -fno-strict-aliasing -lm -s -x c++ -O3 -std=c++11 -Wall -o spellcheck spellcheck.cc

ver:
	g++ -static -fno-optimize-sibling-calls -fno-strict-aliasing -lm -s -x c++ -O3 -std=c++11 -Wall -o spellcheck spellcheck.cc -DVERBOSE

	
clean:
	rm -f spellcheck
	
  
